---
- hosts: elk
  become: True
  tasks:
    - name: set vm.max_map_count to 26214 in sysctl
      sysctl:
         name: vm.max_map_count
         value: 262144
         state: present
         reload: yes

    - name: uninstall appache httpd
      apt:
        name: apache2
        state: absent

    - name: docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      pip:
        name: docker
        state: present

    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports: 
              - 5601:5601
              - 9200:9200
              - 5044:5044
